# Generated by Django 5.0.4 on 2024-06-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_person_images_alter_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
