# Generated by Django 5.0.4 on 2024-06-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_person_email_person_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='address',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='phone',
            new_name='price',
        ),
    ]
