# Generated by Django 5.0.4 on 2024-06-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_rename_address_person_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
