# Generated by Django 5.0.4 on 2024-06-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_alter_person_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='description',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='price',
            new_name='phone',
        ),
    ]
