# Generated by Django 5.0.6 on 2024-06-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_slider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Product',
        ),
    ]
