# Generated by Django 5.0.6 on 2024-06-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_order_total_amount_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Default Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='your_email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='1234567890', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
